### ISSUE TITLE
rest Api?

### ISSUE THREAD

**Issue by Galaxy-Coding** [Mr-KayJayDee/discord-image-generation#9]
It would be nice if there was a json endpoint api for this

**Comment by Mr-KayJayDee** [comment]
> It would be nice if there was a json endpoint api for this

Yeah, but most the apis are very quickly known by everyone. And too used to end up saturated and then they just close.

Before this package there was a rest api yeah, but we closed it to create a package, because we think that it is better for everyone and the code is open source so you can just take the code you need and implement it in your code. 🙃

**Comment by Galaxy-Coding** [comment]
A rest api would make the data way more accessible, for example different languages, e.g js, python, golang, basically **any** language with the ability to make web requests

**Comment by Mr-KayJayDee** [comment]
I understand but that means we have to buy a bigger server to handle more and more request over time and we don't want that because this was the main reason for doing a package.
